// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using torneo_calcetto.EF.Context;

#nullable disable

namespace torneo_calcetto.EF.Migrations
{
    [DbContext(typeof(TorneoCalcettoContext))]
    [Migration("20241113220236_sqaudre_nullable")]
    partial class sqaudre_nullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("torneo_calcetto.EF.Models.Partita", b =>
                {
                    b.Property<int>("IdPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPk"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FaseEliminatoria")
                        .HasColumnType("bit");

                    b.Property<int>("GolCasa")
                        .HasColumnType("int");

                    b.Property<int>("GolOspite")
                        .HasColumnType("int");

                    b.Property<string>("SquadraCasa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SquadraOspite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoPartita")
                        .HasColumnType("int");

                    b.Property<string>("Vincitore")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPk");

                    b.ToTable("Partite", (string)null);
                });

            modelBuilder.Entity("torneo_calcetto.EF.Models.Squadra", b =>
                {
                    b.Property<int>("IdPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPk"));

                    b.Property<int>("DifferenzaReti")
                        .HasColumnType("int");

                    b.Property<int>("GolFatti")
                        .HasColumnType("int");

                    b.Property<int>("GolSubiti")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pareggi")
                        .HasColumnType("int");

                    b.Property<int>("PartiteGiocate")
                        .HasColumnType("int");

                    b.Property<int>("PuntiFatti")
                        .HasColumnType("int");

                    b.Property<int>("Sconfitte")
                        .HasColumnType("int");

                    b.Property<int>("Vittorie")
                        .HasColumnType("int");

                    b.HasKey("IdPk");

                    b.ToTable("Squadre", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
